// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkvsXFRWplmETjS2cjpyqwEg5qTjmKr4',
    appId: '1:593122841067:web:685ed4584f38380ab049ae',
    messagingSenderId: '593122841067',
    projectId: 'redditclone-67e49',
    authDomain: 'redditclone-67e49.firebaseapp.com',
    storageBucket: 'redditclone-67e49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn2TI5GzpiolZiXS6SPIVRr7ei2l2YxYY',
    appId: '1:593122841067:android:4e6bd7a89b4d2ad7b049ae',
    messagingSenderId: '593122841067',
    projectId: 'redditclone-67e49',
    storageBucket: 'redditclone-67e49.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzzlY3gTjhp8Y5Ilw3LMiAqUKAXdIMgKk',
    appId: '1:593122841067:ios:79e70b52fe270af2b049ae',
    messagingSenderId: '593122841067',
    projectId: 'redditclone-67e49',
    storageBucket: 'redditclone-67e49.appspot.com',
    iosBundleId: 'com.example.reddit',
  );
}
